Section "ServerFlags"
	Option "DontZap" "false"
EndSection

Section "InputClass"
	Identifier "Keyboard Defaults"
	MatchIsKeyboard "Yes"
	Option "XkbOptions" "terminate:ctrl_alt_bksp"
EndSection

Section "Device"
	Identifier "Nouveau GT330M via KMS"
	Driver "modesetting"
	Option "AccelMethod" "glamor"
	Option "PageFlip" "true"
EndSection
